name: Deploy Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Nginx
      run: |
        sudo apt update
        sudo apt install -y nginx
        sudo cp $(pwd)/nginx.conf /etc/nginx/nginx.conf
        sudo nginx -t  # Tarkistetaan Nginx-konfiguraation syntaksi
        sudo systemctl restart nginx || sudo systemctl status nginx.service || sudo journalctl -xeu nginx.service

    - name: Get Nginx error log
      run: |
        echo "Nginx Error Log:"
        sudo tail -n 50 /var/log/nginx/error.log
